HERO vs MONSTER (separated functions)

In this game we have 2 objects: HERO and MONSTER. A hero has to go throught a field (400-cell field) to collect hit power, different arms, lifes, abilities and so on. Some where at the end of this way, he/she has to meet and to fight with a monster. They will beat each over and the winner will remain alife.

Functions game_field_hero() and game_field_monster() create 2 matrices. The first (field_h) contains heros location, second (field_m) containes monster and collections location. Heros is 1, monster is 3 and findings (we can change the hero's abilities) are 2. Both, field_h and field_m are global variables.

In [163]:
import numpy as np
import random

def game_field_hero():
    global r
    r = 0
    global c 
    c = 0    
    field = np.zeros((20, 20)) # To create alternativ matrix 20 per 20 with 0's for hero
    field[r][c] = 1 # heros location
    global field_h
    field_h = field
    return field_h

def game_field_monster():
    global field_m
    field = np.zeros((20, 20)) # To create a matrix wih 0's 20 per 20 with 0's for collection and monster
    field [random.randint(15, 18)][random.randint(15, 18)] = 3 # monsters location  
    for i in range (10):
        field [random.randint(0, 15)][random.randint(0, 15)] = 2 # collect hit power, different arms, lifes, abilities...
    global field_m
    field_m = field
    return field_m  

print(game_field_hero())
print(game_field_monster())


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

Function hm_caracteristics(a) generates the initial hero and monster abilities depends on the selected level a (from 1 to 4)


The MONSTER's caracteristics : LIFES - 200 
                              ATTACKS - (hand, foot, sword_1, sword_2, magic attacks type) 
                              DEFEND - % reduction from hero hit
                              
The variable monster_car = [LIFES, ATTACKS[hand, foot, sword, super attacks type], DEFEND]   


The HERO's caracteristics: LIFES = 250 can be completed max 270 
                           ATTACKS (hand, foot, sword_1, sword_2, magic atacks type) 
                           DEFEND  % reduction from monster hit 
                           INSPIRATION (inspiration 1, 2, 3, 4, 5 means +1, +2, +3, +4, +5 for hero's hit power) 
                           DEXTERITY (dexterity 1, 2, 3, 4, 5 means -1, -2, -3, -4, -5 from monster's hit power)
                           
The variable hero_car = [LIFES, ATTACKS[hand, foot, sword_1, sword_2, magic atacks type], DEFEND, INSPIRATION, DEXTERITY] 

LIFES, INSPIRATION and DEXTERITY can be increaesd during the navigation

Both variables are global. 


In [157]:
def hm_caracteristics (a): # depends on the level a to determine the initial hero's and monsters caracteristics
    global hero_car
    hero_car = [250, [2, 3, 5, 10, 15], 0.2, 1, 1]
    global monster_car
    if a == 1: monster_car = [200, [4, 6, 8, 10, 20], 0.1]
    elif a == 2: monster_car = [200, [4, 6, 8, 10, 20], 0.2]
    elif a == 3: monster_car = [200, [4, 6, 8, 10, 20], 0.3]   
    elif a == 4: monster_car = [200, [4, 6, 8, 10, 20], 0.4]
    return monster_car, hero_car

a = int(input("Enter, please, a level from 1 to 4: "))

hm_caracteristics (a)

hero_car

Enter, please, a level from 1 to 4: 2


[250, [2, 3, 5, 10, 15], 0.2, 1, 1]

Function upgrade() is destinated to change the heros abilities. There are 10 cell with value "2". In condition if heros location in field_h has the same coordinates as "2" in field_h we randomly generate a number from 1 to 4 and depends on this number a catacteristic changes.

In [160]:
def upgrade(): # to modify the heros characteristics
    global hero_car
    global r
    global c
    if int(field_m[r, c]) == 2:
        b = random.randint(1, 4)
        print(b)
        if b == 1 and (hero_car[0]+20) <= 270: 
            hero_car[0] = hero_car[0] + 20
            return hero_car
        elif b == 2: 
            hero_car[2] = hero_car[2] + 0.2
            return hero_car
        elif b == 3 and (hero_car[3]+1) <= 5: 
            hero_car[3] = hero_car[3] + 1
            return hero_car
        elif b == 4 and (hero_car[4]+1) <= 5: 
            hero_car[4] = hero_car[4] + 1
            return hero_car

print(upgrade())
print("The heros caracteristics after updating", hero_car) # the hero's caracteristic after each step 

3
[270, [2, 3, 5, 10, 15], 0.2, 2, 2]
The heros caracteristics after updating [270, [2, 3, 5, 10, 15], 0.2, 2, 2]


Function fighting() contains hero's and monster's hits one by one until the result of hero's or monster's wins. The hits formulas take in account the participant caracteristics

In [214]:
def fighting():
    while  hero_car[0] >= 1 and monster_car[0] >=1:
        # hero's hit
        c = random.randint(0, 4)
        monster_car[0] = monster_car[0] - (int(hero_car[1][c]) + hero_car[3])*(1 - monster_car[2])
        print("monster_car lifes = ", monster_car[0])
        # monster's hit
        d = random.randint(0, 4)
        hero_car[0] = hero_car[0] - (int(monster_car[1][d]) - hero_car[4])*(1 - hero_car[2])
        print("hero_car lifes = ", hero_car[0])
    if hero_car[0] < 1: return "The Monster Wins"
    else: return "The Hero Wins"

if (int(field_m[r, c]) == 3):
    print(fighting())


'The Hero Wins'

Function hero_moving(step) alows heros moving. It is possible to move one cell up, down, left, right in our field. If we are out of field the function asks to enter the direction again. The function returns matrix, r and c, which reprezent the row and column value of heros location. The are only one argument "step" - player chooses the step (up, down, left, right).

In [193]:
step = int(input('''Enter, please, a number from 1 to 4: 
1 = "up"
2 = "down"
3 = "left"
4 = "right": '''))

while (step == 2 and (r+1) > 19) or (step == 4 and (c+1) > 19):
    step = input ("""It is not possible to to move in this direction.
#Please choose another option to move up, down, left, right: """)
    
while (step == 1 and (r-1) < 0) or (step == 3 and (c-1) < 0):
    step = input ("""It is not possible to to move in this direction.
#Please choose another option to move up, down, left, right: """)

def hero_moving(step): 
    global r
    global c
    global field_h
    if step == 1 and (r-1) >= 0: r -= 1
    elif step == 2 and (r+1) <= 19: r += 1   
    elif step == 3 and (c-1) >= 0: c -= 1
    elif step == 4 and (c+1) <= 19: c += 1
    field_h = np.zeros((20, 20))
    return field_h, r, c

hero_moving(step)

field_h[r,c] = 1

print(field_h)

Enter, please, a number from 1 to 4: 
1 = "up"
2 = "down"
3 = "left"
4 = "right": 2
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

2. HERO vs MONSTER putting all together (an exammple how does the function work toghether)

In [245]:
# The hero's and monsters matrices creation and visualization

print(game_field_hero())
print(game_field_monster())

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [246]:
# The levvel determination

a = int(input("Enter, please, a level from 1 to 4: "))
hm_caracteristics (a)

Enter, please, a level from 1 to 4: 2


([200, [4, 6, 8, 10, 20], 0.2], [250, [2, 3, 5, 10, 15], 0.2, 1, 1])

In [247]:
#The game itself

while int(field_m[r, c]) != 3: # while the hero did not meet the monster 
    step = int(input('''Enter, please, a number from 1 to 4:  
1 = "up"
2 = "down"
3 = "left"
4 = "right": '''))
    # Hero has to be in the field
    while (step == 2 and (r+1) > 19) or (step == 4 and (c+1) > 19):
        step = input ("""It is not possible to to move in this direction.
#Please choose another option to move up, down, left, right: """)
    while (step == 1 and (r-1) < 0) or (step == 3 and (c-1) < 0):
        step = input ("""It is not possible to to move in this direction.
#Please choose another option to move up, down, left, right: """)
    
    hero_moving(step) # the step itself
    field_h[r,c] = 1
    print(field_h) # the field visualization
    
    upgrade() # in condition if we have some hero's caracteristics update
    print("The heros caracteristics after updating", hero_car) # the hero's caracteristic after each step 

print(fighting()) # when the hero meets the monster tey start to fight. The caracteristics and result are displayed

Enter, please, a number from 1 to 4:  
1 = "up"
2 = "down"
3 = "left"
4 = "right": 4
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0