In [10]:
import numpy as np

a = np.array([1, 4, 5]) # vector
b = np.array([-1, 4, 53]) # vector

c = a + b
print(c)

[ 0  8 58]


https://www.youtube.com/watch?v=eDb6iugi6Uk

In [4]:
d = a*b
print(d)

[ -1  16 265]


In [6]:
m1 = np.array([[1, 4], [-5, 8]]) # matrix
m2 = np.array([[7, -6], [-11, 2]]) # matrix

msum = m1+m2
print(msum)

[[  8  -2]
 [-16  10]]


In [7]:
product = np.dot(m1, m2)
print(product)

[[ -37    2]
 [-123   46]]


In [8]:
zeros = np.zeros((2, 3)) # null matrix
i = np.identity(3)       # identiry matrix
print(zeros)
print(i)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Matrix inverse

In [126]:
a = np.array([[-1, 3], [3, 5]])
b = np.array([[3], [7]])
inv = np.linalg.inv(a) # invers for a

x = np.dot(inv, b)     # multiply invers matrix and b
print(x)

[[0.42857143]
 [1.14285714]]


In [22]:
a = np.array([[1, 2], [3, 4]])

inv = np.linalg.inv(a) # invers for a

print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
a = np.array([[3, 2], [6, 4]])

inv = np.linalg.inv(a) # invers for a

print(inv)

LinAlgError: Singular matrix

In [14]:
a = np.array([[5, -4], [10, -8]])
b = np.array([[6], [-12]])
inv = np.linalg.inv(a) # invers for a
x = np.dot(inv, b)     # multiply invers matrix and b
print(x)


LinAlgError: Singular matrix

In [45]:
a = np.array([[1, 0], [-1, 1]])

inv = np.linalg.inv(a) # invers for a

print(inv)

[[1. 0.]
 [1. 1.]]


In [25]:
m1 = np.array([[4, 2, 2], [3, 2, 1], [-2, -1, -2]]) # matrix
m2 = np.array([[1.5, -1, 1], [-2, 2, -1], [-0.5, 0, -1]]) # matrix

x = np.dot(m2, m1)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
a = np.array([[4, 2, 2], [3, 2, 1], [-2, -1, -2]])
b = np.array([[5], [7], [-3]])
inv = np.linalg.inv(a) # invers for a
x = np.dot(inv, b)     # multiply invers matrix and b
print(x)




[[-2.5]
 [ 7. ]
 [ 0.5]]


In [26]:
a = np.array([[0, 1, 1], [0, -2, -1], [-1, 0, 2]])
b = np.array([[3], [7]])
inv = np.linalg.inv(a) # invers for a
#x = np.dot(inv, b)     # multiply invers matrix and b
print(inv)


[[ 4.  2. -1.]
 [-1. -1. -0.]
 [ 2.  1.  0.]]


In [46]:
a = np.array([[2, 1], [2, -1]])
b = np.array([[1, 1], [0, 1]])
#inv = np.linalg.inv(a) # invers for a
x = np.dot(a, b)     # multiply invers matrix and b
print(x)

[[2 3]
 [2 1]]


# PLU decompozition using scipy


In [47]:
from numpy import *

from scipy.linalg import *

B = np.array([[2, 1], [2, -1]])
# PLU

P, L, U = lu(B)

# outputs true

np.allclose(np.dot(np.dot(P, L), U), B)

P, L, U

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [1., 1.]]),
 array([[ 2.,  1.],
        [ 0., -2.]]))

In [ ]:
import numpy as np
#vectors
a = np.array([1, 4, 5])
b = np.array([-1, 4, 53])
c = a + b # c is vector (0, 8, 58 )
print("Vector sum", c)
d = a * b # d is vector (−1, 16, 265)
print("Elementwise vector product", d)

#arrays
m1 = np.array([[1, 4], [-5, 8]])
m2 = np.array([[7, -6], [-11, 2]])
# msum is array ([[8, −2], [−16, 10]])
msum = m1+m2
print("Matrix sum", msum)
# product is array ([[−37, 2], [−123, 46]])
product = np.dot(m1, m2)
print("Matrix product", product)

#zeros is a null matrix of shape 2x3
zeros = np.zeros((2,3))
print("Null matrix: ", zeros)
#i is an identity matrix of shape 3x3
i = np.identity(3)
print("Identity matrix: ", i)

#matrix inverse and multiplication
a = np.array([[-1, 3], [3, 5]])
b = np.array([[3], [7]])
inv = np.linalg.inv(a)
x = np.dot(inv, b)

from scipy.linalg import lu
B = np.array([[ 0, 0, 1], [0, 2, 2], [3, 0, 4]])
# PLU
P, L, U = lu(B)
# outputs true
np.allclose(np.dot(np.dot(P,L), U), B)

In [ ]:
###Please note, that for higher dimension arrays using numpy.matmult is more preferable

a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
product = np.matmul(a, b) # also can be written as a @ b
print("Matrix product", product)

In [ ]:
### Moreover, numpy  provides many useful methods for matrix elements addition,  finding absolute value, generating random matrices, filtering and much more. For example:

a = np.array([[1,2],[3,4]])
# sum_of_elements is 10
sum_of_elements = np.sum(a)
print("Sum of elements", sum_of_elements)

k = -9
abs_k = np.abs(k) #abs_k is 9
print("Absolute of -9 = ", abs_k)

# random matrix of size 4x4 with values from -15 to 15
m1 = np.random.randint(low=-15,high=15, size=(4, 4))
print("Original matrix", m1)
#replace all values that are greater than 0 with 1
filtered_m1 = np.where(m1 < 0, m1, -1)
print("Replacing non-negative values with -1", filtered_m1)

In [57]:
# random matrix of size 4x4 with values from -15 to 15
m1 = np.random.randint(low=-15,high=15, size=(4, 4))
print("Original matrix", m1)


Original matrix [[ -9   4 -12  -5]
 [  1   2  10  -6]
 [ -6  -1  -2 -12]
 [ -6  -4  -2   1]]


In [58]:
#replace all values that are greater than 0 with 1
filtered_m1 = np.where(m1 < 0, m1, -1)
print("Replacing non-negative values with -1", filtered_m1)

Replacing non-negative values with -1 [[ -9  -1 -12  -5]
 [ -1  -1  -1  -6]
 [ -6  -1  -2 -12]
 [ -6  -4  -2  -1]]


# Practice quiz: operations with matrices

In [79]:
b = np.array([[ -6,  -7,  -5,   0],
       [-15,   2, -13,  -5],
       [  8,   4,  10,   8],
       [ -1,  -9,   7,  -4]])

a = sum(np.where(abs(b) > 5, b, 0))
a

-17

In [80]:
n = np.array([[ -4,  -1,   3,  -7,   6,  -9,   5,  -9,  -7,   0],
       [-12,   3, -12,  -7,   2,  -4,   8,  13,   9,   3],
       [ -2,  -1, -15, -10,   7,   5,   7, -13,  -9,   6],
       [  7,  11,  -5,  -6,  -9,  -1,   3,  10, -15,  -6],
       [ -3,  -4,   4, -13,   4, -13,  10,  -6,  -8,  13],
       [  7, -13,  -4,   3,   4,  13, -13,   4,  -9, -10],
       [ -5,  13,  -9, -15,  11,   2,   7, -14, -14,   2],
       [ -4,  -6,  12,  10,  13,  -3,  12, -15,   5,  -2],
       [ -1,   8,   3,   7,  11,  -3,   6,  12,  12, -13],
       [ 12,  11,  12,  11,   1, -14,   2,   6,  -9,  -3]])
z = np.array([[-15,   5, -15,  10,  -3,  12,  -6, -15,   6,   3],
       [ 12,  -4,   6, -11,   5,   3,   3,  12, -15,  -6],
       [-11, -11, -10,   9,  -8, -14, -14,   7,  -2,  11],
       [  5,  -4,  11,   0,   8,  -9, -15, -11,   7, -10],
       [ -6,  -9,  -3, -13, -11,  -9,   7,  -7,   9,   4],
       [ 10,  12,   4,  -7,   1,   0,  -1,  11,  -4,  11],
       [-14,   2,  -8,  11,  -9,   5, -14,  10,  -6,  -9],
       [ -5,  10, -10,  -1,  -9, -12,  12,  14,   4,   2],
       [ -1, -13,  10,  11,  12, -14,   9,  12,  12,  -5],
       [  2,   6, -13,  -5,  -2,  -2,   0,  14,   7,  14]])

In [81]:
np.matmul(n, z)

array([[-164, -172, -127,  -30, -196,  147, -106, -155, -124,   -6],
       [  81,   69,   76, -100,  -22, -170,  497,  563,   25, -201],
       [ 129,  233,  -31, -309,  -97,  515,   78, -107, -154,   58],
       [   7,  404, -228,  -84, -161,  439,   32,   16, -432, -103],
       [-342,  -41, -495,   52, -362,  185,  -98,   99,  -58,  182],
       [  55,  310,   34, -162,  -68,   71,   94, -529,  166,  214],
       [ 199,   75,  -29, -504, -196,  536,  103,   12, -473,   31],
       [-304, -524,   93,  198,  -89, -267, -521, -220,  155, -116],
       [-165, -335,  186,   58,  -41, -448,  131,  135,   93, -349],
       [-326, -174, -299,  124, -188,  -29, -388, -292,  -92, -161]])

In [82]:
###Please note, that for higher dimension arrays using numpy.matmult is more preferable

a = np.array([-1, 5, 1, 4, 6])
b = np.array([0, 8, -3, 4, -1])
product = np.matmul(a, b) # also can be written as a @ b
print("Matrix product", product)

Matrix product 47


In [83]:
a = np.array([[3, 1, -2], [1, 1, 4]])
b = np.array([[0, 2, -3], [2, 1, 0], [1, 1, 1]])
c = np.array([[4, 1, -2], [2, 0, 0], [-4, 0, -1]])
d = np.array([[2, -1], [0, -5], [-1, 0]])

sumbc = b + c
product1 = np.dot(a, sumbc)
product2 = np.dot(sumbc, d)

np.sum(product2)


-15

In [84]:
a = np.array([[1, 5, -2, 1], [3, 16, -3, 11], [0, 0, 6, 10], [-5, -25, 10, -1]])
b = np.array([[4], [19], [2], [-12]])
inv = np.linalg.inv(a)
x = np.dot(inv, b)
print(x)

[[-4.0000000e+00]
 [ 1.0658141e-14]
 [-3.0000000e+00]
 [ 2.0000000e+00]]


In [85]:
a = np.array([[1, -2, 3], [-3, 0, 2], [1, -1, 4]])
b = np.array([[5], [2], [6]])
inv = np.linalg.inv(a)
x = np.dot(inv, b)
print(x)

[[ 0.23529412]
 [-0.35294118]
 [ 1.35294118]]


In [86]:
4/17

0.23529411764705882

In [87]:
-6/17

-0.35294117647058826

In [88]:
23/17

1.3529411764705883

In [89]:
a = np.array([[0, -2], [4, 7]])
b = np.array([[1], [2]])
inv = np.linalg.inv(a)
x = np.dot(inv, b)
print(x)

[[ 1.375]
 [-0.5  ]]


In [90]:
11/8

1.375

In [100]:
a = np.array([[3, 5, -1], [-4, 1, 2], [0, 1, 0]])

inv = np.linalg.inv(a)

print(a)

[[ 3  5 -1]
 [-4  1  2]
 [ 0  1  0]]


In [156]:
a = np.array([[1, 1, 1, 1], [-2, 3, 2, 1], [0, 1, 1, 1], [1, 3, 1, -2]])
b = np.array([[1, 0, -1, 0], [7, 3, -12, -1], [-12, -5, 21, 2], [5, 2, -8, -1]])
inv = np.linalg.inv(a)

#print(inv)
x = np.dot(a, inv)
d = np.dot(a, b)

print(d)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [149]:
a = np.array([[1, 0.5, -5.5], [4/23, 0, 0], [2, 1.5, -11.5]])
b = np.array([[3, 5, -1], [-4, 1, 2], [0, 1, 0]])
inv = np.linalg.inv(b)
x = np.dot(a, inv)
print(inv)

[[  1.    0.5  -5.5]
 [  0.    0.    1. ]
 [  2.    1.5 -11.5]]


In [104]:
a = np.array([[1, 1, 0], [2, 1, 1], [-1, 0, 1]])
b = np.array([[-1], [1], [-1]])
inv = np.linalg.inv(a)
x = np.dot(inv, b)
print(x)

[[ 1.5]
 [-2.5]
 [ 0.5]]


In [146]:
B = np.array([[1, 3, 1, 0], [1, 0, -1, 2], [0, 0, 1, 2], [-1, 1, 0, 1]])
C = np.array([[1, 2, 3, -1]])

BT = np.transpose (B)

CT = np.transpose (C)

x = np.dot(CT, C)
x
y = np.dot(BT, B)
y
z = np.dot(x, y)
z

array([[  6,  30,  15,  -6],
       [ 12,  60,  30, -12],
       [ 18,  90,  45, -18],
       [ -6, -30, -15,   6]])

In [124]:
B = np.array([[-3, 4, 0], [1, -3, 2], [-6, 7, 1]])
# PLU

P, L, U = lu(B)

# outputs true

np.allclose(np.dot(np.dot(P, L), U), B)

P, L, U

array([[ 1.        ,  0.        ,  0.        ],
       [-0.16666667,  1.        ,  0.        ],
       [ 0.5       , -0.27272727,  1.        ]])