In [7]:
#matrix rank - nonzero rows in matrix

In [12]:
import numpy as np
import numpy.linalg as LA

In [9]:
matrixA = np.array([[1, 4, 5],
                    [-5, 8, 9],
                    [-12, 8, 8]])
print("The Rank of a Matrix: ", np.linalg.matrix_rank(matrixA))

The Rank of a Matrix:  2


In [19]:
matrixA = np.array([[4, 8, 1, -9],
                    [0, 5, 1, 3],
                    [2, 9, 1, 4],
                    [1, 7, 1, 3.5]])
print("The Rank of a Matrix: ", np.linalg.matrix_rank(matrixA))

The Rank of a Matrix:  3


In [13]:
import numpy as np
import numpy.linalg as LA

A = np.array([[1, 4, 5, -1], 
              [2, 9, 12, 1],
              [0, 1, 2, 3]])

rank = LA.matrix_rank(A)
print(rank)

2


In [14]:
import numpy as np
import numpy.linalg as LA

A = np.array([[1, 2, 3], 
              [2, 4, 6],
              [3, 6, 9]])

rank = LA.matrix_rank(A)
print(rank)

1


In [19]:
import numpy as np
import numpy.linalg as LA

A = np.array([[12, 18], 
              [18, 21]])

rank = LA.matrix_rank(A)
print(rank)

2


In [20]:
import numpy as np
import numpy.linalg as LA

A = np.array([[3, -1, 1, 9], 
              [-3, 4, 1, 1],
              [6, 5, 2, 8],
              [1, 1, 1, 1]])

rank = LA.matrix_rank(A)
print(rank)

4


In [15]:
import numpy as np
import numpy.linalg as LA

A = np.array([[-10, 13, 12, 0], 
              [3, -3, 0, 3],
              [-17, 23, 24, 3]])

rank = LA.matrix_rank(A)
print(rank)

2


In [8]:
import numpy as np
import numpy.linalg as LA

A = np.array([[1, -3, 1, -2, 9], 
              [0, 1, -3, -5, 4],
              [-2, 7, -5, -1, -14],
              [1, -5, 7, 8, 1]])

rank = LA.matrix_rank(A)
print(rank)

2


In [14]:
import numpy as np
import numpy.linalg as LA

A = np.array([[6, 1, -3, 5], 
              [2, 39, -17, 3],
              [4, -9, 2, 3],
              [-30, -5, 15, -25]])

b = [1, -13, 4, -5]

x = LA.lstsq(A, b)
x


C:\Users\User\AppData\Local\Temp/ipykernel_10776/967945676.py:11: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x = LA.lstsq(A, b)


(array([ 0.15537738, -0.32153719,  0.06607686,  0.11750069]),
 array([], dtype=float64),
 2,
 array([4.94387067e+01, 3.65351102e+01, 1.77768214e-15, 6.56854718e-16]))

In [18]:
matrixA = np.array([[1, 8, 1, -9],
                    [0, 5, 1, 3],
                    [2, 9, 1, 4],
                    [1, 7, 1, 3.5]])

M = matrixA[:, :-1]
print(M)

[[1. 8. 1.]
 [0. 5. 1.]
 [2. 9. 1.]
 [1. 7. 1.]]
