# Task 6

In [4]:
import numpy as np

m1 = np.array([[3, 2], [-1, -2], [1, -2]]) # matrix
m2 = np.array([[1, 0, 1, 1/2], [0, 1, -1, -5/4]]) # matrix

product = np.dot(m1, m2)
print(product)

[[ 3.  2.  1. -1.]
 [-1. -2.  1.  2.]
 [ 1. -2.  3.  3.]]


In [5]:
import numpy as np

m1 = np.array([[-3, 4], [1, -3], [-1, -2]]) # matrix
m2 = np.array([[1, 0, -8/5], [0, 1, -6/5]]) # matrix

product = np.dot(m1, m2)
print(product)

[[-3.0000000e+00  4.0000000e+00  8.8817842e-16]
 [ 1.0000000e+00 -3.0000000e+00  2.0000000e+00]
 [-1.0000000e+00 -2.0000000e+00  4.0000000e+00]]
